name: publish

on:
  push:
    branches:
      - "main"

jobs:
  build-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - run: dotnet run --project ./BlogStudio/BlogStudio.csproj -c Release
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wwwroot
          keep_files: true